name: CI

on:
  push:
    branches:
      - main  # Запускаем CI при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускаем CI при создании пул-реквеста в ветку main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # CI/CD клонирует ваш репозиторий.
        uses: actions/checkout@v2

      - name: Set up Python # Устанавливает Python.
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies # Устанавливает зависимости (Pydantic и pytest).
        run: |
          python -m pip install --upgrade pip
          pip install pydantic pytest

      - name: Run tests # Запускает тесты с помощью pytest.
        run: |
          pytest test_models.py