name: CI

on:
  push:
    branches:
      - Alchemy  # Запускаем CI при пуше в ветку
  pull_request:
    branches:
      - Alchemy  # Запускаем CI при создании пул-реквеста в ветку

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code # CI/CD клонирует ваш репозиторий.
        uses: actions/checkout@v2

      - name: Set up Python # Устанавливает Python.
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies # Устанавливает зависимости (Pydantic и pytest).
        run: |
          python -m pip install --upgrade pip
          pip install pydantic pytest

      - name: Run tests
        env:
          SUPER_ADMIN_USERNAME: ${{ secrets.SUPER_ADMIN_USERNAME }}
          SUPER_ADMIN_PASSWORD: ${{ secrets.SUPER_ADMIN_PASSWORD }}
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          USERNAME_DB: ${{ secrets.USERNAME_DB }}
          PASSWORD_DB: ${{ secrets.PASSWORD_DB }}
          BASE_URL_LOGIN: ${{ secrets.BASE_URL_LOGIN }}
          BASE_URL: ${{ secrets.BASE_URL }}
          LOGIN_DATA: ${{ secrets.LOGIN_DATA }}

        run: |
          echo "BASE_URL=$BASE_URL" >> $GITHUB_ENV
          echo "HOST=$HOST" >> $GITHUB_ENV
          echo "PORT=$PORT" >> $GITHUB_ENV    
      

      - name: Run tests # Запускает тесты с помощью pytest.
        run: |
          pytest